// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Answer;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.CheckerError;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Error;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Input;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Output;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \contests\{contestId}\submissions\{submissionId}\{testName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTestNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The answer property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Answer.AnswerRequestBuilder Answer
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Answer.AnswerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkerError property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.CheckerError.CheckerErrorRequestBuilder CheckerError
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.CheckerError.CheckerErrorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The error property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Error.ErrorRequestBuilder Error
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Error.ErrorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The input property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Input.InputRequestBuilder Input
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Input.InputRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The output property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Output.OutputRequestBuilder Output
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.Output.OutputRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.WithTestNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTestNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contests/{contestId}/submissions/{submissionId}/{testName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Submissions.Item.Item.WithTestNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTestNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contests/{contestId}/submissions/{submissionId}/{testName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
