// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Competitions.Item.Participants;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Competitions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \competitions\{competitionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCompetitionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The participants property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Competitions.Item.Participants.ParticipantsRequestBuilder Participants
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Competitions.Item.Participants.ParticipantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Competitions.Item.WithCompetitionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCompetitionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/competitions/{competitionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Competitions.Item.WithCompetitionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCompetitionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/competitions/{competitionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
