// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions.Item;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions
{
    /// <summary>
    /// Builds and executes requests for operations under \submissions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubmissionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.submissions.item collection</summary>
        /// <param name="position">submissionId</param>
        /// <returns>A <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions.Item.WithSubmissionItemRequestBuilder"/></returns>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions.Item.WithSubmissionItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("submissionId", position);
                return new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions.Item.WithSubmissionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions.SubmissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubmissionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/submissions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Submissions.SubmissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubmissionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/submissions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
