// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Item.Problems.Item.Statement
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TEX")]
        #pragma warning disable CS1591
        TEX,
        #pragma warning restore CS1591
        [EnumMember(Value = "PDF")]
        #pragma warning disable CS1591
        PDF,
        #pragma warning restore CS1591
        [EnumMember(Value = "BINARY")]
        #pragma warning disable CS1591
        BINARY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MARKDOWN")]
        #pragma warning disable CS1591
        MARKDOWN,
        #pragma warning restore CS1591
    }
}
