// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AdditionalSolutionCheckResult_verdict
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        FAILED,
        #pragma warning restore CS1591
    }
}
