// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CompilerLimit : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The compilerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompilerName { get; set; }
#nullable restore
#else
        public string CompilerName { get; set; }
#endif
        /// <summary>The idlenessLimit property</summary>
        public long? IdlenessLimit { get; set; }
        /// <summary>The memoryLimit property</summary>
        public long? MemoryLimit { get; set; }
        /// <summary>The outputLimit property</summary>
        public long? OutputLimit { get; set; }
        /// <summary>The timeLimit property</summary>
        public long? TimeLimit { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models.CompilerLimit"/> and sets the default values.
        /// </summary>
        public CompilerLimit()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models.CompilerLimit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models.CompilerLimit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models.CompilerLimit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compilerName", n => { CompilerName = n.GetStringValue(); } },
                { "idlenessLimit", n => { IdlenessLimit = n.GetLongValue(); } },
                { "memoryLimit", n => { MemoryLimit = n.GetLongValue(); } },
                { "outputLimit", n => { OutputLimit = n.GetLongValue(); } },
                { "timeLimit", n => { TimeLimit = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("compilerName", CompilerName);
            writer.WriteLongValue("idlenessLimit", IdlenessLimit);
            writer.WriteLongValue("memoryLimit", MemoryLimit);
            writer.WriteLongValue("outputLimit", OutputLimit);
            writer.WriteLongValue("timeLimit", TimeLimit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
