// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContestReportSettings_showScore
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NEVER")]
        #pragma warning disable CS1591
        NEVER,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCORED_TESTS")]
        #pragma warning disable CS1591
        SCORED_TESTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCORED_TESTS_AND_SAMPLES")]
        #pragma warning disable CS1591
        SCORED_TESTS_AND_SAMPLES,
        #pragma warning restore CS1591
    }
}
