// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContestDescription_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "USUAL")]
        #pragma warning disable CS1591
        USUAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIRTUAL")]
        #pragma warning disable CS1591
        VIRTUAL,
        #pragma warning restore CS1591
    }
}
