// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContestReportSettings_showAnswer
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NEVER")]
        #pragma warning disable CS1591
        NEVER,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL_FAILED")]
        #pragma warning disable CS1591
        ALL_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRST_FAILED")]
        #pragma warning disable CS1591
        FIRST_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL_PASSED")]
        #pragma warning disable CS1591
        ALL_PASSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONLY_SAMPLES")]
        #pragma warning disable CS1591
        ONLY_SAMPLES,
        #pragma warning restore CS1591
    }
}
