// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MultiRunReport_globalError
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NO_TESTS_IN_PROBLEM")]
        #pragma warning disable CS1591
        NO_TESTS_IN_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_CHECKER_IN_PROBLEM")]
        #pragma warning disable CS1591
        NO_CHECKER_IN_PROBLEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "GLOBAL_TL")]
        #pragma warning disable CS1591
        GLOBAL_TL,
        #pragma warning restore CS1591
    }
}
