// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NeuripsSubmissionReport_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "WAITING")]
        #pragma warning disable CS1591
        WAITING,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINISHED")]
        #pragma warning disable CS1591
        FINISHED,
        #pragma warning restore CS1591
    }
}
