// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ParticipantStatus_contestState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FINISHED")]
        #pragma warning disable CS1591
        FINISHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        IN_PROGRESS,
        #pragma warning restore CS1591
    }
}
