// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RegisterGroupRequest_roles
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ADMIN")]
        #pragma warning disable CS1591
        ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "JUDGE")]
        #pragma warning disable CS1591
        JUDGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "COACH")]
        #pragma warning disable CS1591
        COACH,
        #pragma warning restore CS1591
        [EnumMember(Value = "COORDINATOR")]
        #pragma warning disable CS1591
        COORDINATOR,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTICIPANT")]
        #pragma warning disable CS1591
        PARTICIPANT,
        #pragma warning restore CS1591
        [EnumMember(Value = "STARTING_ALLOWED")]
        #pragma warning disable CS1591
        STARTING_ALLOWED,
        #pragma warning restore CS1591
        [EnumMember(Value = "OWNER")]
        #pragma warning disable CS1591
        OWNER,
        #pragma warning restore CS1591
    }
}
