// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.My
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortByQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ID")]
        #pragma warning disable CS1591
        ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCORE")]
        #pragma warning disable CS1591
        SCORE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTICIPANT_NAME")]
        #pragma warning disable CS1591
        PARTICIPANT_NAME,
        #pragma warning restore CS1591
    }
}
