// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.All;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.My;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions
{
    /// <summary>
    /// Builds and executes requests for operations under \contests\neurips\{contestId}\submissions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubmissionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.All.AllRequestBuilder All
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The my property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.My.MyRequestBuilder My
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.My.MyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.SubmissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubmissionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contests/neurips/{contestId}/submissions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Contests.Neurips.Item.Submissions.SubmissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubmissionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contests/neurips/{contestId}/submissions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
