// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.Capacity;
using Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.Introspect;
namespace Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service
{
    /// <summary>
    /// Builds and executes requests for operations under \service
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServiceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The capacity property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.Capacity.CapacityRequestBuilder Capacity
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.Capacity.CapacityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The introspect property</summary>
        public global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.Introspect.IntrospectRequestBuilder Introspect
        {
            get => new global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.Introspect.IntrospectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.ServiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServiceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/service", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Texnokaktus.ProgOlymp.YandexContestIntegrationService.Client.Service.ServiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServiceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/service", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
